image: "rust:latest"

variables:
    RUST_BACKTRACE: "FULL"

stages:
  - build
  - release

build_linux:
  stage: build
  artifacts:
    paths:
      - target/release/mlc
  script:
    - cargo build --verbose --release  

build_windows:
  stage: build
  image: servercore:ltsc2019
  tags:
    - shared-build_windows
    - windows
    - windows-1809
  artifacts:
    paths:
      - target/release/mlc
  script:
    - echo hello
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

test_latest:
    stage: build
    script:
      - cargo test --all --verbose

test_nightly:
    stage: build
    image: rustlang/rust:nightly
    script:
      - cargo test --all --verbose
    allow_failure: true

release_github_artifact:
  stage: release
  image: golang:latest
  script:
    - go get github.com/aktau/github-release
    - github-release release --user becheran --repo mlc --tag $CI_COMMIT_TAG
    - github-release upload --user becheran --repo mlc --tag $CI_COMMIT_TAG --name "mlc" --file target/release/mlc
  only:
    - tags

release_docker:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t becheran/mlc .
    - version="${CI_COMMIT_TAG:1}"
    - docker tag becheran/mlc becheran/mlc:$version
    - docker push becheran/mlc
  only:
    - tags
