[package]
name = "mlc"
version = "0.13.0"
authors = ["Armin Becher <becherarmin@gmail.com>"]
edition = "2018"
description = "The markup link checker (mlc) checks for broken links in markup files."
keywords = [ "link-checker", "broken", "markup", "html", "markdown"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/becheran/mlc"

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-open-issues = { repository = "becheran/mlc" }
is-it-maintained-issue-resolution = { repository = "becheran/mlc" }

[dependencies]
clap = {version = "2.33.1", features = ["yaml"]}
log = "0.4.8"
simplelog = "0.6.0"
walkdir = "2.3.1"
regex = "1.3.9"
lazy_static = "1.4.0"
url = "2.1.1"
colored = "1.9.3"
async-std = "1.6.2"
reqwest = {version="0.10.6", features = ["native-tls-vendored"] }
tokio = {version="0.2.21", features = ["rt-threaded", "macros"] }
futures = "0.3.5"
wildmatch = "1.0.11"

[dev-dependencies]
ntest = "0.7.1"
criterion = "0.3.2"

[[bench]]
name = "benchmarks"
harness = false
